version: '3.8'

services:
  identity_agriculture_service:
    build:
      context: .
      dockerfile: dockerfiles/agriculture-identity.dockerfile
    image: dat0309/agriculture_identities
    volumes:
      - ./backend/FASTAPI-AGRICULTURE-IDENTITY:/agriculture-identity
    ports:
      - '8004:8080'
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/frontend.dockerfile
  #   volumes:
  #     - react_build:/react/build
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/nginx.dockerfile
  #   image: daz/nginx-identity-agriculture
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - react_build:/var/www/react
  #   ports:
  #     - '80:80'
  #     - '443:80'
  #   depends_on:
  #     - auth_service
  #     - app_service
  #     - ai_service
  #     - frontend
volumes:
  react_build: